/**
 * prd-html 的设计样式（复刻原始 PRD 文档的版式）。
 *
 * 这份 CSS 属于模板本身，不放进 core/html-kit —— 设计规范跟着文档模板走，
 * 模板之间不复用样式。
 *
 * 设计令牌：ink #202c27 / muted #69746d / line #dce2dc / green #247356
 */

export const PRD_CSS = [
  "/* ── 令牌 ───────────────────────────────────── */",
  ":root{--ink:#202c27;--muted:#69746d;--line:#dce2dc;--green:#247356;--head:#edf2ed;--zebra:#fbfcfa;--rule:#bacabf}",
  "*{box-sizing:border-box}",
  "html{scroll-behavior:smooth}",
  "body{margin:0;background:#efefeb;color:var(--ink);font:16px/1.85 \"PingFang SC\",\"Noto Sans CJK SC\",\"Noto Sans SC\",\"Microsoft YaHei\",sans-serif;-webkit-font-smoothing:antialiased}",
  "article{max-width:1120px;margin:38px auto 70px;background:#fff;padding:64px 72px 78px;border:1px solid #e0e3dc}",

  "/* ── 页眉与标题区 ───────────────────────────── */",
  ".masthead{display:flex;justify-content:space-between;gap:16px;font-size:12px;letter-spacing:.08em;color:var(--muted);border-top:3px solid var(--ink);padding-top:12px;margin-bottom:36px}",
  "h1{font-size:36px;line-height:1.3;font-weight:650;letter-spacing:-.03em;margin:0 0 14px}",
  ".tagline{font-size:24px;line-height:1.5;margin:0 0 26px;color:var(--green);font-weight:500}",
  ".doc-meta{font-size:13px;color:var(--muted);padding-bottom:25px;border-bottom:1px solid var(--line);margin:0 0 0}",

  "/* ── 阅读目录 ───────────────────────────────── */",
  ".reading-toc{padding:6px 0;margin:28px 0 48px}",
  ".reading-toc span.toc-label{font-size:12px;color:var(--muted);display:block;margin-bottom:8px}",
  ".reading-toc a{font-size:14px;display:inline-block;text-decoration:none;color:var(--green);margin:0 24px 5px 0}",
  "/* 标题较长时改成两列编号目录：竖排更好扫读，两列不会占掉半屏 */",
  ".reading-toc.is-list{counter-reset:toc;column-count:2;column-gap:56px;margin-top:6px}",
  ".reading-toc.is-list a{display:block;margin:0 0 7px;break-inside:avoid;line-height:1.5}",
  ".reading-toc.is-list a::before{counter-increment:toc;content:counter(toc,decimal-leading-zero);color:var(--muted);font-size:11px;font-variant-numeric:tabular-nums;margin-right:10px;letter-spacing:.02em}",
  "@media(max-width:760px){.reading-toc.is-list{column-count:1}}",
  "@media print{.reading-toc.is-list{column-count:2}}",

  "/* ── 标题层级 ───────────────────────────────── */",
  "h2{font-size:28px;line-height:1.45;margin:76px 0 24px;padding-top:24px;border-top:2px solid var(--ink);font-weight:650;scroll-margin-top:24px}",
  "h3{font-size:22px;line-height:1.55;margin:48px 0 18px;font-weight:600;scroll-margin-top:24px}",
  "h4{font-size:18px;line-height:1.5;margin:30px 0 12px;font-weight:600;scroll-margin-top:24px}",

  "/* ── 正文 ───────────────────────────────────── */",
  "p{margin:14px 0 20px}",
  "strong{font-weight:650}",
  "a{color:var(--green);text-underline-offset:3px}",
  "code{font:12px/1.65 ui-monospace,SFMono-Regular,Menlo,monospace;overflow-wrap:anywhere;background:#f3f5f1;padding:2px 4px;border-radius:3px}",
  ".can-do{color:var(--green);font-weight:600}",
  ".doc-list{margin:14px 0 22px;padding-left:1.5em}",
  ".doc-list li{margin:0 0 8px}",
  "blockquote{margin:25px 0 30px;padding:15px 22px;border-left:3px solid var(--green);background:#f4f7f2;font-size:17px;line-height:1.9}",

  "/* ── 表格 ───────────────────────────────────── */",
  ".table-wrap{margin:23px 0 27px}",
  "table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:14px;line-height:1.8}",
  "th{text-align:left;background:var(--head);font-weight:600;padding:12px 14px;border-top:1px solid var(--rule);border-bottom:1px solid var(--rule)}",
  "td{vertical-align:top;padding:14px;border-bottom:1px solid var(--line);overflow-wrap:anywhere}",
  "th:first-child,td:first-child{width:21%}",
  "tr:nth-child(even) td{background:var(--zebra)}",
  "td code{font-size:11px}",
  "table strong{font-weight:600}",
  ".cell-list{margin:0;padding-left:1.4em}",
  ".cell-list li{padding-left:2px;margin:0 0 7px}",
  ".cell-list li:last-child{margin-bottom:0}",
  ".cell-list li::marker{color:var(--muted);font-variant-numeric:tabular-nums}",
  ".cell-text{display:block;margin-top:4px}",
  ".cell-group + .cell-group{margin-top:18px;padding-top:16px;border-top:1px solid var(--line)}",
  ".cell-group-title{margin-bottom:10px;color:var(--ink)}",
  "td > p:first-child{margin-top:0}",
  "td > p:last-child{margin-bottom:0}",

  "/* ── 状态圆标（支持 / 不支持 / 不适用） ─────── */",
  ".support-status{-webkit-print-color-adjust:exact;print-color-adjust:exact;display:inline-flex;align-items:baseline;gap:6px;font-weight:500;line-height:1.75}",
  ".support-yes{color:#247356}.support-no{color:#b74440}.support-na{color:#748079}",
  ".status-icon{display:inline-flex;align-items:center;justify-content:center;flex:none;width:16px;height:16px;border-radius:50%;background:currentColor;position:relative;top:2px;font:600 12px/1 Arial,sans-serif}",
  ".support-yes .status-icon{background:#247356;color:#fff}",
  ".support-no .status-icon{background:#b74440;color:#fff;font-size:15px}",
  ".support-na .status-icon{background:#eef1ed;color:#748079;font-size:17px}",

  "/* ── 表格版式（列宽） ───────────────────────── */",
  ".capability-table th:nth-child(1),.capability-table td:nth-child(1){width:16%}",
  ".capability-table th:nth-child(2),.capability-table td:nth-child(2){width:35%}",
  ".capability-table th:nth-child(3),.capability-table td:nth-child(3){width:12%}",
  ".capability-table th:nth-child(4),.capability-table td:nth-child(4){width:19%}",
  ".capability-table th:nth-child(5),.capability-table td:nth-child(5){width:18%}",
  ".capability-table td,.field-support-table td{padding-top:15px;padding-bottom:15px}",
  ".field-support-table th:nth-child(1),.field-support-table td:nth-child(1){width:15%}",
  ".field-support-table th:nth-child(2),.field-support-table td:nth-child(2){width:20%}",
  ".field-support-table th:nth-child(3),.field-support-table td:nth-child(3){width:16%}",
  ".field-support-table th:nth-child(4),.field-support-table td:nth-child(4){width:49%}",
  ".field-support-table tbody td:first-child{font-weight:600}",
  ".field-support-table .field-group-start:not(:first-child) td{border-top:2px solid var(--rule)}",
  ".goals-table th:nth-child(1),.goals-table td:nth-child(1){width:10%}",
  ".goals-table th:nth-child(2),.goals-table td:nth-child(2){width:27%}",
  ".goals-table th:nth-child(3),.goals-table td:nth-child(3){width:63%}",
  ".goals-table tbody td:first-child{color:var(--green);font-size:17px}",
  ".acceptance-table th:nth-child(1),.acceptance-table td:nth-child(1){width:24%}",
  ".acceptance-table th:nth-child(2),.acceptance-table td:nth-child(2){width:33%}",
  ".acceptance-table th:nth-child(3),.acceptance-table td:nth-child(3){width:43%}",
  ".acceptance-tools-table th:nth-child(1),.acceptance-tools-table td:nth-child(1){width:27%}",
  ".acceptance-tools-table th:nth-child(2),.acceptance-tools-table td:nth-child(2){width:12%}",
  ".acceptance-tools-table th:nth-child(3),.acceptance-tools-table td:nth-child(3){width:27%}",
  ".acceptance-tools-table th:nth-child(4),.acceptance-tools-table td:nth-child(4){width:34%}",
  ".acceptance-fields-table th:nth-child(1),.acceptance-fields-table td:nth-child(1){width:20%}",
  ".acceptance-fields-table th:nth-child(2),.acceptance-fields-table td:nth-child(2){width:35%}",
  ".acceptance-fields-table th:nth-child(3),.acceptance-fields-table td:nth-child(3){width:45%}",
  ".acceptance-skill-table th:nth-child(1),.acceptance-skill-table td:nth-child(1){width:32%}",
  ".acceptance-skill-table th:nth-child(2),.acceptance-skill-table td:nth-child(2){width:20%}",
  ".acceptance-skill-table th:nth-child(3),.acceptance-skill-table td:nth-child(3){width:48%}",
  ".acceptance-index-table th:nth-child(1),.acceptance-index-table td:nth-child(1){width:28%}",
  ".acceptance-index-table th:nth-child(2),.acceptance-index-table td:nth-child(2){width:56%}",
  ".acceptance-index-table th:nth-child(3),.acceptance-index-table td:nth-child(3){width:16%}",
  "table[class^=\"acceptance-\"] tbody td:first-child strong{color:var(--green)}",
  "table[class^=\"acceptance-\"] td{padding-top:16px;padding-bottom:16px}",

  "/* ── 图 ─────────────────────────────────────── */",
  "figure{margin:30px -6px 34px;break-inside:avoid;border:1px solid var(--line)}",
  "figure svg{width:100%;height:auto;display:block}",
  "figcaption{padding:3px 15px 9px;text-align:right;font-size:11px;color:var(--muted)}",
  "footer{border-top:2px solid var(--ink);padding-top:16px;margin-top:60px;font-size:12px;color:var(--muted)}",

  "/* ── 窄屏 ───────────────────────────────────── */",
  "@media(max-width:760px){body{background:#fff}article{margin:0;border:0;padding:30px 20px}h1{font-size:29px}h2{font-size:25px;margin-top:55px}h3{font-size:21px}table{min-width:690px}.table-wrap{overflow-x:auto}figure{overflow:auto}figure svg{min-width:740px}.masthead{letter-spacing:0;font-size:10px}}",

  "/* ── 打印（浏览器直接导出 A4） ──────────────── */",
  "@media print{@page{size:A4;margin:16mm 14mm 17mm}body{background:#fff;font-size:10pt;line-height:1.75}article{max-width:none;margin:0;border:0;padding:0}.masthead{margin-bottom:20px}h1{font-size:27pt}.tagline{font-size:16pt}.doc-meta{font-size:8pt}h2{font-size:19pt;margin:32px 0 14px;break-before:page}h3{font-size:14pt;margin:25px 0 12px}h4{font-size:11pt}h1,h2,h3,h4{break-after:avoid}p{orphans:3;widows:3}table{font-size:8.2pt;line-height:1.7}th,td{padding:7px 8px}tr{break-inside:avoid}thead{display:table-header-group}.table-wrap{overflow:visible}figure{margin:16px 0;break-inside:avoid}figcaption{display:none}blockquote{font-size:10pt;break-inside:avoid}nav{display:none}code,td code{font-size:7.5pt}a{text-decoration:none;color:inherit}footer{font-size:8pt}}",
].join("\n");
